### ISSUE TITLE
missing RSS feed icon

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#1]
Hello,

First, thanks a lot for this wonderful theme.

I can see that you need to be logged in to see the 'RSS feed' icon. Is it by design?

J.

**Comment by kalvn** [comment]
Hi,
You're completely right, that's a mistake.
It's now fixed in the master branch thanks to this commit: https://github.com/kalvn/Shaarli-Material/commit/c6734da3cafc86b6fb54af1ad213f727512d25ce.
Thanks for the feedback :)

**Comment by jeekajoo** [comment]
thanks much :+1:
