### ISSUE TITLE
Large pictures overflow in mobile view

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#104]
Hi, I've noticed a small bug after updating to the latest version in #95. It might have been present before, I just noticed it now. 

When an image is inserted as a markdown image (`![title](link)`), if the image is wider than the card, it's overflowing to the right.

It would be nice to resize the image to the card's inner width by maintaining the aspect ratio. 

![Screenshot_20200409-063307](https://user-images.githubusercontent.com/21174107/78858415-abeff180-7a2c-11ea-91c7-691ea83f3256.jpg)

**Comment by kalvn** [comment]
There you go https://github.com/kalvn/Shaarli-Material/commit/42561fc1b1aeb5d1b754cd735888f0c7678c2492

**Comment by immanuelfodor** [comment]
Thank you for this fix as well, it looks good!
