### ISSUE TITLE
The tags list is truncated on mobile

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#105]
Hi, this issue is present for a while, I can/could live with it, but would be nice to fix it. 

In the mobile view, when there are more tags on a card than space to display all of them, the tag list is truncated by showing 3 dots (...) instead of the remaining tags. However, the tag list is also scrollable, as if there are more tags to display but these are hidden. 

Here is a screenshot video of the issue: https://www.sendvid.com/rabev31z

I like navigating by tags but sometimes this is limited by not showing some crucial tags.

**Comment by kalvn** [comment]
What browser are you using? I tried with a Chromium based one + with Firefox, both on Android, and it works fine.

**Comment by immanuelfodor** [comment]
It's Brave which is also Chromium based. Tried deleting the cache, but it didn't help. 

(Checked with FF as well, it's fine there, the extra tags are displayed upon scrolling the list.)

**Comment by kalvn** [comment]
I think I found a suitable solution that doesn't affect too much the display, only if a link has a high number of tags. They now distribute on several line if there's not enough space.

![image](https://user-images.githubusercontent.com/6149640/78990948-075ad600-7b38-11ea-9668-255b43616a67.png)

**Comment by immanuelfodor** [comment]
This could definitely boost tag navigation, I usually have 6-10 tags, but no more than your example.
I think it's better to have it than to only have access to 3-4 like before.

**Comment by kalvn** [comment]
Ok it's merged into master, I close the ticket then.

**Comment by immanuelfodor** [comment]
Awesome, the update looks fantastic, thank you!
