### ISSUE TITLE
Revert some CSS changes?

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#106]
Hi, I bumped into another issue, it seems there are some CSS changes regarding the card content, is there a way to get them back to the previous state, or at least fix some of the current ones?

I'm testing with this text:

```
# h1 test

text

## h2 test 

text

### h3 test

**bold test**

ul test:
- first item
    - inner item
    - inner item 2
- second item
- third item

#### h4 test

asd
```

It looks like this now:

![image](https://user-images.githubusercontent.com/21174107/78866363-8cae8f80-7a3f-11ea-85ff-e727b9ab4130.png)

The hX headers changed their sizes, lost their paddings, etc. I regularly used h3 titles because of their previous size, now these are indistinct from regular text. On the other hand, h1-s were too great to be usable, so now h1-s are the perfect size, which maybe semantically better than using only h3-s in a card. But when editing the markdown, h3-s had three #-s which were better separators of content block. What do you think, may we revert to the previous titles format?

(ul-s were also displayed wrong, but I did a hard reload on the page that solved it after the theme update.)

**Comment by kalvn** [comment]
https://github.com/kalvn/Shaarli-Material/commit/20ddcf2f126b84c6c8aeb1805728f12c373fc9ca should do the trick :)

**Comment by immanuelfodor** [comment]
Perfect, looks great now, thanks!
