### ISSUE TITLE
Search pop-up not working in v0.11.0

### ISSUE THREAD

**Issue by paulgit** [kalvn/Shaarli-Material#107]
I just upgraded to the latest theme and the search pop dialog is not working. This can be seen at [Paul Git's Links](https://links.paulg.it/?).

I have tried Safari, Firefox and Brave and each browser exhibits the same issue so I can only think it's an issue with my server setup. Do you have any ideas on where I can start to look?

**Comment by kalvn** [comment]
Hi @paulgit , I had a look at your server but it seems to be broken. Can you put it back online first? I had a quick look earlier and it seemed like the whole JavaScript was broken but I could investigate yet.

**Comment by paulgit** [comment]
Hi @kalvn , thanks for your reply. I should have closed this ticket because I decided to use the Bookmarking app in Nextcloud instead.
