### ISSUE TITLE
upscale favicon ?

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#11]
Hi,

What about upscaling the favicon ?

* I went here https://www.google.com/design/icons/#ic_stars
* Downloaded PNGs of 48dp (ic_stars_black_48dp.zip)
* Edited ic_stars_black_48dp/web/ic_stars_black_48dp_2x.png with Gimp
* Changed color profile to RGB
* Filled the star with color #02a8f3

Result:
https://fralef.me/links/tpl/material/images/favicon.ico (96x96px, transparent background preserved, 1bpp, 1bit-alpha, 2-slot palette, uncompressed, 2.4K)
https://fralef.me/links/tpl/material/images/favicon.png (96x96px, transparent background preserved, compression level 9, 653 bytes)

Let me know ;)
J.

**Comment by kalvn** [comment]
That's right, the default favicon is damn small.
I took a bigger version of the favicon and generated the .png and ico files, plus images for mobile OS.
I hope everything's fine, don't hesitate to comment, otherwise.

I'll keep this ticket open for a while.

**Comment by jeekajoo** [comment]
Great!
Now I'm wondering if we still need this: ```<link rel="shortcut icon" href="tpl/material/./images/favicons/favicon.ico">```
An outdated github (https://github.com/audreyr/favicon-cheat-sheet) tells that:
```
Create at least this:
Sizes 	Name 	Purpose
16x16 & 32x32 	favicon.ico 	Default required by IE. Chrome and Safari may pick ico over png, sadly. 
```
I have doubts..
Thanks

**Comment by kalvn** [comment]
I believe we do. I'll just reupload it to make sure it reaches at least 48x48 so it stays clean.
By the way thanks for the link, it's full of great information :)

**Comment by jeekajoo** [comment]
favicon.ico is only required for IE < 11 as older version do not support PNG version of favicon: https://en.wikipedia.org/wiki/Favicon#File_format_support
http://realfavicongenerator.net/faq#why_ico_not_declared suggests not to declare favicon.ico, just to drop it at the root if you want to satisfy old IE users.

**Comment by kalvn** [comment]
I agree on this but as this is only a theme, I cannot provide files to drop at the root of the installation. But I can definitely provide a file and ask users to move it (in the the README file for example).
A good suggestion to make on the official Shaarli repo would be to offer the possibility (via the settings menu) to change the favicon. And to give the possibility to theme developers to intercept this change and apply it also on the theme's files.

**Comment by kalvn** [comment]
I close this as it's in standby, depending on future developments.
