### ISSUE TITLE
user.css cannot modify plugins.css because loaded too early

### ISSUE THREAD

**Issue by dajare** [kalvn/Shaarli-Material#111]
I have been using Shaarli-Material for a few years now, but just today attempted to modify the css for the `blockquote` element in a link/note description.

The rules for this in my case are found in `/plugins/markdown/markdown.css` (since I have Markdown enabled for descriptions), but when I added a rule for this specifying `.markdown blockquote {}` in my user.css ... nothing happened.

I noted that user.css [gets loaded before the css from plugins][1], so I simply dropped the user.css loading to line 51 (current) following the "plugins.css" loop in [includes.html][2].

And now all is well. :)

Is there a better way to address this? (I notice that putting [user.css last is the arrangement in Shaarli's default template][3].) Or could this re-ordering be implemented for future releases of Shaarli-Material?

---

**P.s.** I see now that this can also go in Shaarli-Material's "[extra.html][e]" file. That's good, but my sense is that it's probably still preferable for "user.css" to be able to do it's job properly.

[e]: https://github.com/kalvn/Shaarli-Material#add-custom-resources
[3]: https://github.com/shaarli/Shaarli/blob/8f80821820e4024c899d762efb0d2ab3426afc6c/tpl/default/includes.html#L18
[1]: https://github.com/kalvn/Shaarli-Material/blob/d437fbed87c03bc1117104943dc79bb0033534e1/material/includes.html#L47
[2]: https://github.com/kalvn/Shaarli-Material/blob/master/material/includes.html

**Comment by kalvn** [comment]
You are fully right! I just published a fix on the dev branch to ensure that `user.css` always has precedence on plugins CSS files. It'll be included in the next release.
