### ISSUE TITLE
[Feature request] Shaarli as a PWA (service workers) 

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#112]
Hi @kalvn, 

I've just bumped into Unmark (https://github.com/cdevroe/unmark) and it sounds like an awesome feature to be able to install it as an "app" through service workers. Not only you can use it like an app for browsing content, but also you can share content "into the installed app". There is a demo in the middle of this page: https://www.notion.so/Unmark-Help-How-to-add-bookmarks-cd5893f118ed40cd8400275e49f40d51

Checking the source, it seems you only need to have a manifest JSON and there you need to have a share target declaration, and some JS code to declare the necessary service workers. 

From this guide, it looks it can be implemented on the frontend, this is why I open this ticket here and not in the main Shaarli repo:  https://web.dev/progressive-web-apps/

Would you consider looking into PWAs to make Shaarli "installable" and better integrated with Android share through your theme?

**Comment by kalvn** [comment]
It looks like a good idea, I'll take a look at the documentation about sharing data with a PWA.

**Comment by kalvn** [comment]
Unfortunately, the `manifest.webmanifest` file [must be at the root of your web server](https://web.dev/add-manifest/#create). It makes it impossible to handle the PWA thing in Shaarli Material.

But you can still propose the idea to the Shaarli team.

**Comment by immanuelfodor** [comment]
Thank you very much for the research time, I've opened a new Shaarli issue: https://github.com/shaarli/Shaarli/issues/1544
