### ISSUE TITLE
align public and private link titles

### ISSUE THREAD

**Issue by bdeshi** [kalvn/Shaarli-Material#113]
hi, can you consider removing the `margin-left` [here](https://github.com/kalvn/Shaarli-Material/blob/d437fbed87c03bc1117104943dc79bb0033534e1/src/scss/components/_page-linklist.scss#L72) and moving the private link bg image a bit (like in the image below) so that the public and private link titles are aligned?

![image](https://user-images.githubusercontent.com/3525376/82924423-20abca80-9f9e-11ea-9c23-2a874100e714.png)

**Comment by kalvn** [comment]
I'll see what I can do :)

**Comment by kalvn** [comment]
The change will be part of the next release v0.12.0 ;)
