### ISSUE TITLE
Compatibility with Shaarli v0.12.0-beta

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#115]
Hi @kalvn,

According to https://github.com/shaarli/Shaarli/pull/1511 we need to check and maybe update our plugins and themes to stay compatible with the changes in Shaarli's routing and templating. After upgrading Shaarli to latest master, nothing is displayed on the UI, a blank page is shown as the Material theme is not yet updated. Could you please look into the changes and fix the new errors caused by the refactoring?

The docker logs for the first fatal error that stop the page from rendering:

```
shaarli    | 2020/08/30 08:13:21 [error] 11#11: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function isLoggedIn() in /var/www/shaarli/tmp/includes.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php:82
shaarli    | Stack trace:
shaarli    | #0 /var/www/shaarli/inc/rain.tpl.class.php(175): include()
shaarli    | #1 /var/www/shaarli/tmp/error.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php(4): RainTPL->draw('./includes')
shaarli    | #2 /var/www/shaarli/inc/rain.tpl.class.php(190): include('/var/www/shaarl...')
shaarli    | #3 /var/www/shaarli/application/render/PageBuilder.php(237): RainTPL->draw('error', true)
shaarli    | #4 /var/www/shaarli/application/front/controller/visitor/ShaarliVisitorController.php(66): Shaarli\Render\PageBuilder->render('error', '')
shaarli    | #5 /var/www/shaarli/application/front/controller/visitor/ErrorController.php(43): Shaarli\Front\Controller\Visitor\ShaarliVisitorController->render('error')
shaarli    | #6 [internal function]: Shaarli\Front\Controller\Visitor\ErrorController->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Error))
shaarli    | #7 /var/www/shaarli/vendor/slim/slim/Slim/App.php(728): call_" while reading response header from upstream, client: 192.168.1.3, server: , request: "GET /? HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "shaarli.local", referrer: "https://shaarli.local/?9qeqtA"
shaarli    | 192.168.1.3 - shaarli [30/Aug/2020:08:13:21 +0000] "GET /? HTTP/1.1" 500 2660 "https://shaarli.local/?9qeqtA" "Mozilla/5.0 ..."

```

**Comment by kalvn** [comment]
Hi @immanuelfodor,
Yes I definitely need to take some time to update the theme, I'll try to take a look either today or during the coming week, at least to make it work with the latest master from Shaarli. I'll keep you updated :)

**Comment by ArthurHoaro** [comment]
@kalvn Let me know if I can help.

**Comment by kalvn** [comment]
@ArthurHoaro thanks! Actually I have a question: do you know if there's a way to retrieve the current URL path (`$_SERVER['REQUEST_URI']`) from templates?

I tried to access the `$_SERVER` variable from within templates but it cause errors (on contrary to `$_GET` which works fine). I need this to highlight current page in the `tag.sort.html` file.

**Comment by ArthurHoaro** [comment]
It's not exactly what you asked for, but you could use `{$_PAGE_}` which could fit your use case and are also used by plugins. However I need to fix an unnecessary breaking change in these values, as mentioned in the other thread.

**Comment by kalvn** [comment]
The branch **support-v012** was just finalized. I tested it pretty intensively with Shaarli v0.12.0-beta and found no issues so far. I didn't create a release yet but if anyone wants to do some test on his side, I would greatly appreciate :)

I'll keep testing for a few days on my own and release it when Shaarli v0.12.0 is released.

**Comment by immanuelfodor** [comment]
Did a git checkout to the new branch, works fine, looks awesome 🎉

However, I can't login at all after a logout. It seems to be a general Shaarli issue @ArthurHoaro on the master branch as the docker image was built from scratch. Deleted ipbans file, did a browser cache delete, used a different browser, nothing helped.

**Comment by immanuelfodor** [comment]
I can't login even with the default template, this is an important info I think. The login redirect seems to be weird: 

```
shaarli    | 192.168.1.3 - shaarli [02/Sep/2020:02:59:11 +0000] "POST /login?returnurl=%2F HTTP/1.1" 302 0 "https://shaarli.local/login?returnurl=%2F" "Mozilla/5.0...
shaarli    | 192.168.1.3 - shaarli [02/Sep/2020:02:59:11 +0000] "GET /login?returnurl=%2Flogin%3Freturnurl%3D%252F HTTP/1.1" 200 12197 "-" "Mozilla/5.0... 
```

**Comment by immanuelfodor** [comment]
Maybe https://github.com/shaarli/Shaarli/pull/1536 needs to be merged quick 😃

**Comment by immanuelfodor** [comment]
When editing a share on mobile, the FAB is shown and it is out of place: 

![Screenshot_20200902-052149](https://user-images.githubusercontent.com/21174107/91928462-63d3b300-ecdc-11ea-9013-842cbef95aa0.jpg)

**Comment by ArthurHoaro** [comment]
@immanuelfodor I merged shaarli/Shaarli#1536, it should fix the issue you had previously.

**Comment by ArthurHoaro** [comment]
> The branch support-v012 was just finalized

@kalvn Awesome! You rule!

**Comment by kalvn** [comment]
@immanuelfodor I found the responsible line: https://github.com/kalvn/Shaarli-Material/blob/support-v012/material/page.header.html#L173

I'll fix that asap :)

**Comment by kalvn** [comment]
It's fixed with the last commit.

**Comment by immanuelfodor** [comment]
Tested with the latest support-v012 branch, it's fixed, thanks! :)

**Comment by immanuelfodor** [comment]
Hmm, I think I've found another bug: the CSS/JS resources are loaded without `/` at the beginning of the URL, so it becomes `/admin/shaare/plugins/markdown_toolbar/includes/bootstrap_markdown/js/bootstrap-markdown.js` for example which breaks the edit/add page resources as these are now requested from a folder too deep:

![image](https://user-images.githubusercontent.com/21174107/92307586-c2788580-ef97-11ea-9f98-749efe795758.png)

These weren't 404 URLs 2 days ago, so something must broke in the meantime.

**Comment by immanuelfodor** [comment]
Or maybe Shaarli:master introduced a change that results in `PluginManager::$PLUGINS_PATH` becoming "shash-less"? 😀 @ArthurHoaro

**Comment by kalvn** [comment]
I think it's not related to Shaarli Material.

I would say plugin developers must ensure external resources are added with the base path, as it's done here for example: https://github.com/kalvn/shaarli2mastodon/blob/master/shaarli2mastodon.php#L75

**Comment by immanuelfodor** [comment]
Wow, thanks for the example, I'm adding this to my plugins. Sorry for suspecting a bug here.

**Comment by kalvn** [comment]
Thanks but credit goes to https://github.com/shaarli/Shaarli/blob/master/plugins/wallabag/wallabag.php#L48 😉

**Comment by ArthurHoaro** [comment]
Just to give a little more info about *why*:

   - we don't know if Shaarli is installed under a subfolder or not, so we can't use `'/' . PluginManager::$PLUGINS_PATH`
   - before `v0.12` every route were on the same folder level (`domain.tld/shaarli/?do=route`), so relative path worked fine. Now routes can be on multiple levels (e.g. `/daily` and `/admin/*` routes), so it requires to manually set the absolute path.

**Comment by immanuelfodor** [comment]
Thanks for the insights! Based on this knowledge I also opened a shaarli-favicons PR to fix the same issue, shaaring is caring :) https://github.com/trailjeep/shaarli-favicons/pull/3

**Comment by immanuelfodor** [comment]
https://github.com/shaarli/Shaarli/pull/1558 happened in the meantime, so I'll also revert any related changes. @kalvn said in https://github.com/shaarli/Shaarli/issues/1548#issuecomment-691662186 that Shaarli Material has been also updated accordingly, so I think this ticket can be closed finally.

**Comment by immanuelfodor** [comment]
Updated all my plugins, they now work according to PR https://github.com/shaarli/Shaarli/pull/1558 Also https://github.com/shaarli/Shaarli/issues/1545 works fine with the theme. I think the `support-v012` branch here can be also closed, it's up-to-date with master. Thank you all for being supportive over the years! ❤️
