### ISSUE TITLE
I've lost my FAB

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#117]
Hi, somewhere at or after the latest rewrite, my FAB button got lost, and I haven't found it since then. It's not in the DOM, so I don't think it's being blocked by a plugin. I've added a pinned post in my Shaarli to link to the Add Shaare form, this is how I circumvented this issue so far to be able to add new links from the web. Could you please check where did the FAB go? 😃

**Comment by kalvn** [comment]
If by FAB button you mean the button to add new links, yes, it's related to issue #118 

I just need to get an alternative from Shaarli dev team and I'll publish a fix.

**Comment by immanuelfodor** [comment]
Yup, it's the Floating Action Button aka. FAB: https://material.io/components/buttons-floating-action-button :) 

Thank you!

**Comment by pascollin** [comment]
In page.header.html $_PAGE variable seems empty
_{$displayAddNewLinkIcon=(($is_logged_in || $openshaarli) && in_array($_PAGE_, array('linklist', 'tools', 'tag.cloud', 'tag.list', 'picwall', 'daily')))}_
Dirty workaround : replace this line by the following :
_{$displayAddNewLinkIcon=(($is_logged_in || $openshaarli))}_
Now the button is displayed on all pages when logged in.

**Comment by immanuelfodor** [comment]
It was previously fixed here, so this workaround is like a revert: https://github.com/kalvn/Shaarli-Material/issues/115#issuecomment-685266681

**Comment by immanuelfodor** [comment]
I've rebuilt my Shaarli using the `support-v012` branch, and now the FAB is working again just as before. Thank you for the unnoticed changes in November :)
