### ISSUE TITLE
provide button for firefox social

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#12]
Hi,
would it be possible to add Firefox Social button ?
```
✚Add to Firefox social ⇐ Click on this button to add Shaarli to the "Share this page" button in Firefox.
```
See demo: http://shaarlidemo.tuxfamily.org/Shaarli/?do=tools (demo/demo)

Feature introduced with https://github.com/shaarli/Shaarli/commit/d33c5d4c3b9c70441391a08e8bcb2a8c639a4635

Thanks
J.

**Comment by kalvn** [comment]
Hello,
I tried your demo but it doesn't work. Nothing happens when I press the button. However, the code is correct, according to Firefox Social API documentation. Is there something to activate in Firefox itself? I tried examples given by Mozilla (like GOAL.com) and it works.

**Comment by jeekajoo** [comment]
yep, demo doesn't work.
it works on my shaarli. 
1 advantage over bookmarklet: you bypass CRSF protections (e.g. on github)

**Comment by kalvn** [comment]
I'm not against adding it but I need to make it work before. And it really sounds like the implementation of the current master branch of Shaarli doesn't work. What did you change on yours?

**Comment by jeekajoo** [comment]
I did nothing for it to work on my shaarli. Are you using Firefox >= 29?

**Comment by kalvn** [comment]
Yes I use the last version (39) and it's working fine for other Firefox Social API implementations given as examples on the documentation https://support.mozilla.org/en-US/kb/add-social-features-firefox-sidebar

**Comment by jeekajoo** [comment]
So we found out that:
> Your Shaarli instance must be hosted on an HTTPS (SSL/TLS secure connection) enabled server for Firefox Share to work. Firefox Share will not work over plain HTTP connections.

https://github.com/shaarli/Shaarli/issues/310

**Comment by kalvn** [comment]
Great, thanks a lot for investigation. I'll implement it and disable the button if the instance is accessed via http rather than https.

**Comment by jeekajoo** [comment]
committed: https://github.com/kalvn/Shaarli-Material/commit/7a9bc83fb70a1c6d0ea90f14f9d87e35a40e0a45
