### ISSUE TITLE
Description and title is not extracted from shared links

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#120]
Moved here from the main Shaarli repo: https://github.com/shaarli/Shaarli/issues/1653

It seems to be a Material theme issue, working fine with the default theme:

![image](https://user-images.githubusercontent.com/21174107/100518084-a26bf300-318f-11eb-82c9-7c5ff876895d.png)

![image](https://user-images.githubusercontent.com/21174107/100518099-b4e62c80-318f-11eb-8d57-7c14126dcad2.png)

 kalvn commented 12 minutes ago

> I'm pretty sure this is because metadata is now retrieved asynchronously, therefore using JavaScript which is part of the theme, not the core of Shaarli.
> 
> It means I have to handle that part on my own. I'll work on it soon.

**Comment by kalvn** [comment]
Thanks for re-opening!

I just noticed that there's now a setting to stick to the regular sync metadata retrieving.

In your `data/config.json.php` file you can put `enable_async_metadata` to `false`, at least until I adapt the theme.

**Comment by immanuelfodor** [comment]
Well, I indeed have it on `true` but `false` is even worse :D 

![image](https://user-images.githubusercontent.com/21174107/100518632-ff1cdd00-3192-11eb-9e87-21b5bde9de52.png)

![image](https://user-images.githubusercontent.com/21174107/100518615-e14f7800-3192-11eb-8704-9c6a4acad2f7.png)

This is what I get after clicking the add link button.

```
strlen() expects parameter 1 to be string, boolean given
/var/www/shaarli/application/front/controller/admin/ShaarePublishController.php230
#0 /var/www/shaarli/application/front/controller/admin/ShaarePublishController.php(230): strlen(false)
#1 /var/www/shaarli/application/front/controller/admin/ShaarePublishController.php(165): Shaarli\Front\Controller\Admin\ShaarePublishController->buildFormData(Array, true, Object(Slim\Http\Request))
#2 /var/www/shaarli/application/front/controller/admin/ShaarePublishController.php(37): Shaarli\Front\Controller\Admin\ShaarePublishController->displayForm(Array, true, Object(Slim\Http\Request), Object(Slim\Http\Response))
#3 [internal function]: Shaarli\Front\Controller\Admin\ShaarePublishController->displayCreateForm(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/shaarli/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/shaarli/application/front/ShaarliMiddleware.php(55): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/shaarli/application/front/ShaarliAdminMiddleware.php(25): Shaarli\Front\ShaarliMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#8 [internal function]: Shaarli\Front\ShaarliAdminMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/shaarli/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Array, Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/shaarli/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/shaarli/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/shaarli/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/shaarli/index.php(176): Slim\App->run(true)
#19 {main}
```

Maybe I should reopen that issue for Arthur.

**Comment by ArthurHoaro** [comment]
You should be able to use Shaarli's `assets/common/js/metadata.js` with no or only minor changes if you want to support this feature.

**Comment by immanuelfodor** [comment]
I've rebuilt my Shaarli using the `support-v012` branch, and I've seen that there is a new addition to the JS file regarding the metadata retrieval: https://github.com/kalvn/Shaarli-Material/compare/support-v012

However, title and description are still not loaded with `"retrieve_description": true, "enable_async_metadata": true`.

**Comment by kalvn** [comment]
The last commit should fix this issue.

**Comment by immanuelfodor** [comment]
It works wonderfully, thank you!
