### ISSUE TITLE
French version for The Daily Shaarli

### ISSUE THREAD

**Issue by Cristophe** [kalvn/Shaarli-Material#121]
There is no french translation for:

- The Daily Shaarli  (must be "Le Quotidien Shaarli")
- All links of one day in a single page. ("Tous les liens d'un jour sur une page.")
- Previous day  ("jour précédent")
- Next day  ("jour suivant")

**Comment by kalvn** [comment]
This will be supported in v0.12.1, I'll release a beta soon.

**Comment by kalvn** [comment]
Fixed in [v0.12.1](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.12.1).
