### ISSUE TITLE
Broken picture wall

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#122]
I've rebuilt my Shaarli using the `support-v012` branch, and although many issues are now solved, I've bumped into a new one. 

The picture wall contains broken images as the following URL is being tried to load which is obviously 404: https://shaarli.local/$%7Broot_path%7D/cache/thumb/14ad5266c72782bdc806364df4516335/7fb84dc39d194b47d128e9270664f2ca05d881ae125801.jpg

![image](https://user-images.githubusercontent.com/21174107/103413954-10834b80-4b7c-11eb-9e1c-7de3c9c83236.png)

This is the faulty line: https://github.com/kalvn/Shaarli-Material/compare/support-v012#diff-888961afedb9f3851c84f430957d3b6ed8a1979f7ab1e6a8436ccc9a5744358cR26

I suppose you meant `base_path` instead of `root_path` just as at: https://github.com/kalvn/Shaarli-Material/compare/support-v012#diff-ce61678773fc44021d7fc23f45fc7498ddb97fa267d95b97d10b9d117e1c3913R178

**Comment by ArthurHoaro** [comment]
`${root_path}` -> `{$root_path}`, I have made this mistake a few times.

**Comment by kalvn** [comment]
That was a tricky one, thanks for the notice :D

https://github.com/kalvn/Shaarli-Material/commit/491a3f39c33a95ab02b48d3a082da3d42e332183 fixes it.

**Comment by immanuelfodor** [comment]
Thank you, it's perfect now.
