### ISSUE TITLE
An always-404 tag pill appears upon search

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#123]
I've rebuilt my Shaarli using the `support-v012` branch, and although many issues are now solved, I've bumped into a new one. To be honest, I think this bug was also present before but since I've tested my Shaarli for bugs now, I've found it.

Upon search for tags, an extra empty pill is appended to the list which is always pointing to a 404 page:

![image](https://user-images.githubusercontent.com/21174107/103414093-ba62d800-4b7c-11eb-95a4-a1008784d34f.png)

![image](https://user-images.githubusercontent.com/21174107/103414122-d797a680-4b7c-11eb-84cc-d44683c89a4e.png)

I suppose this pill would like to be a "remove all" function or something like that but is now malfunctioning.

**Comment by kalvn** [comment]
This will be fixed with v0.12.1.

**Comment by immanuelfodor** [comment]
With the latest commits, I don't experience this issue anymore, the surplus X tag is gone. Thank you very much!
