### ISSUE TITLE
Undefined variable for 0.12.1

### ISSUE THREAD

**Issue by Draky50110** [kalvn/Shaarli-Material#126]
Hello.

Little message in header : 
` Notice: Undefined variable: _PAGE_ in /home/XXXX/links/tmp/page.header.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php on line 2`

Any clue ?
Thanks.

**Comment by kalvn** [comment]
Shaarli Material is not yet ready for Shaarli v0.12.1 as stated in the README.md file. Nevertheless, you can use the last commit of the support-v012 branch, it should fix this particular issue.
