### ISSUE TITLE
Update the build instructions to match the new version

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#128]
Please update the build instructions (https://github.com/kalvn/Shaarli-Material/tree/support-v012#build-for-production) as it seems outdated since https://github.com/kalvn/Shaarli-Material/commit/da29c7c0e5db2e8a70a781fbc93b58ff10757d3b

At first, I was not aware of the change, so I tried to install the missing gulp locally but then it said no gulpfile, so I checked the commits, and it seems there was a change with the build tool.

**Comment by immanuelfodor** [comment]
I managed to build it with `npm run-script build` instead of the gulp build command.

**Comment by kalvn** [comment]
Thanks for the notice.

I insist on the fact that what's not on the `master` branch is currently in dev and is not meant to be used for production. I worked quite a lot yesterday on splitting the huge unique JS file into modules and indeed I didn't update yet the build instructions. But the change of build tools appears in the commit message.

I just updated the README and the CHANGELOG.

**Comment by immanuelfodor** [comment]
Since I do a lot of testing lately with Shaarli, my CI is building the latest commits. I only build manually when either Arthur or you fix one of the relevant issues, so athough I'm on bleeding edge, my Shaarli is fairly stable until some new fix comes out that I'm interested in. This morning, I reconfigured something else in my CI that involved a rerun of the pipeline, and so I observed it broke. I'm not familiar with rollup and their docs seemed to be extensive, and they have lots of command line flags, that's why I reported it. Then I got the idea, maybe you also use some flags that you don't want to forget, and maybe created a build script for that, that's when I found the npm script later. So I accidentally found this change, and not by following all commits all the time 😃

**Comment by kalvn** [comment]
No worries and again, thanks for your strong testing, you're helping me a lot :)

I just want to ensure you know that I sometimes don't push everything at the same time and that branches other than master remain somehow experimental. When working on a big feature that I need to split over several days, I still prefer to push at least once a day even if things aren't perfect.
