### ISSUE TITLE
Undefined Variable Error When Adding Link

### ISSUE THREAD

**Issue by mdrockwell** [kalvn/Shaarli-Material#129]
I receive the following error whenever I try to add a link to Shaarli (edited to remove my exact path):

Notice: Undefined variable: index in /bookmark/tmp/editlink.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php on line 23

The link still saves properly — I can see the saved link on other devices. This is with the latest version of Shaarli — 0.12.1 — and the latest beta release of the Material theme — 0.12.1.

![106464535-c507da00-6466-11eb-97d5-66bba9f9be95](https://user-images.githubusercontent.com/42454301/106503512-ba176e80-6493-11eb-8e0e-2dea64226ba7.jpeg)

**Comment by kalvn** [comment]
Thanks for the feedback. This issue is know and was fixed since then (https://github.com/kalvn/Shaarli-Material/commit/778bcf649c7f582a4143af8dcbcd599fdf3a517b) but I didn't make another release since then. I'll do that tonight and let you know when it's ready.

**Comment by kalvn** [comment]
The last release solves the issue.
