### ISSUE TITLE
Add a floating edit button when logged and displaying a shaarlink #enhancement

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#13]
Hi Kalvn,

Would it be possible to add a "Edit" floating button while viewing a link (example : http://shaarlidemo.tuxfamily.org/Shaarli/?OOHCbg)
We could replace the current "Add" button by this "Edit" button, maybe.

Thanks
J.

**Comment by kalvn** [comment]
That's a good idea. But Material Design guidelines expect only one floating button at a time so we either have to remove the add button and replace it by the edit button, as you suggested, or to find another solution. I'll think about it very soon.

**Comment by kalvn** [comment]
I found no elegent way of including such button so I close the issue. I'll keep this in mind for the future anyway.
