### ISSUE TITLE
Odd modal (?) popups with 0.12.1

### ISSUE THREAD

**Issue by dajare** [kalvn/Shaarli-Material#130]
I just upgraded my "Material" Shaarli instance to 0.12.1, and it looks **great**. :) Thanks for the fix and update for this version!

I've got some odd behaviour. Every time I have a page-load of any kind (list view, individual bookmark, tag cloud, etc. etc.) I **always** get two popups in the bottom right of the screen:

<img width="446" alt="shaarli-wot" src="https://user-images.githubusercontent.com/40625/107889097-895e1d00-6f08-11eb-9a21-66fe483d24c8.png">

I close them ... next page load, there they are again! I've searched both the Shaarli and Shaarli-Material repos, but **cannot** find this code in either of them. 😕 It looks like it might be related to [this line in the `page.header.html` file][1] maybe? and possible with [this related commit][2]?

I have another instance of Shaarli running 0.12.1 with my modded version of the default template, and it doesn't have this behaviour. Any ideas? I hope so! Thanks!

---

The code looks like this, if this helps (with a little context):

```
    <form id="hidden-tag-form" class="hidden" method="GET" name="tagfilter" action="/sitename/">
        <input type="hidden" name="searchtags" id="tagfilter_value" value=""/>
    </form>

    <div class="notifications">
      <div class="notification is-danger">
        <button class="notification-close"><i class="mdi mdi-close"></i></button>
        Hello this is short content
      </div>
      <div class="notification is-warning">
        <button class="notification-close"><i class="mdi mdi-close"></i></button>
        Hello this is long content but really something long, I mean REALLY long like hell you know?
      </div>

      

      

      

      
    </div>
```

[1]: https://github.com/kalvn/Shaarli-Material/blob/ccb7a777ff24d625b1ace251f0c0ac36e78d2a50/material/page.header.html#L190
[2]: https://github.com/kalvn/Shaarli-Material/commit/ccb7a777ff24d625b1ace251f0c0ac36e78d2a50

**Comment by kalvn** [comment]
Hi @dajare , thanks a lot for your feedback. My bad, it's something that I forgot to remove after my tests when I compiled the zip and tar.gz files attached to the release. 🤦‍♂️

It's now solved, I just updated zip and tar.gz files attached to the release v0.12.1: https://github.com/kalvn/Shaarli-Material/releases/tag/v0.12.1

You can now safely download them. Thanks again and sorry for this bug.

**Comment by dajare** [comment]
All good! Thanks for the quick fix. Much appreciated!
