### ISSUE TITLE
Missing notification style

### ISSUE THREAD

**Issue by gingerbeardman** [kalvn/Shaarli-Material#132]
Using the default theme: when you import bookmarks you see a notification that it was successful.

The notification does not appear when using Material, so the import function seems to have not worked as there is no feedback (it probably has worked, and you can browser your bookmarks)

<img width="721" alt="Screenshot 2022-02-21 at 21 30 19" src="https://user-images.githubusercontent.com/49612/155027892-207a71f2-7a82-4474-9b55-5a38e0deb5c8.png">

**Comment by kalvn** [comment]
Hi @gingerbeardman 

Sorry for the late reply. I tried to reproduce the issue but couldn't. I did an import locally and could see the success notification:

![image](https://user-images.githubusercontent.com/6149640/159168375-ecbefeff-3ad3-4427-a821-2a0b7ecbc3b7.png)

Do you have the latest version of Shaarli and of Shaarli-Material installed?

If so, can you please help me to reproduce?

**Comment by gingerbeardman** [comment]
Sorry I missed your comment on this issue

**Comment by kalvn** [comment]
No problem, I hope you found a solution.

**Comment by gingerbeardman** [comment]
I did, probably not what you expect: I stopped using Shaarli
