### ISSUE TITLE
Last commit was back then in 2021

### ISSUE THREAD

**Issue by nicolasdanelon** [kalvn/Shaarli-Material#133]
Hey! 👋🏼 is this project dead?
IMHO this is the most beautiful theme for shaarli.. but las commit was two years ago. Is there any new shaarli feature missing? do you need help to add some features?

**Comment by kalvn** [comment]
It's not dead! I adapt to the development pace of Shaarli itself with sometimes a couple of weeks/months delay.

I actually started a branch to work on the v0.12.2 support recently: https://github.com/kalvn/Shaarli-Material/tree/support-v0.12.2

I didn't work on it recently so not sure that all features are implemented yet but if you see something specific missing, feel free to create a dedicated ticket.

**Comment by nicolasdanelon** [comment]
@kalvn thanks for the reply. will close this ticket :) I'm happy to read those news
