### ISSUE TITLE
On edit : delete button first in source code

### ISSUE THREAD

**Issue by timovn** [kalvn/Shaarli-Material#15]
On edit, the the delete button is the first "submit" button in source code.
This causes the browser to delete the post when the user hits "enter".

To fix : change type="submit" to type="button" on both delete and cancel buttons.

Other pages might be subject to this behaviour too. Default Shaarli is not.

**Comment by kalvn** [comment]
Thanks for the feedback. This bug has already been reported (see issue https://github.com/kalvn/Shaarli-Material/issues/5) and fixed on the master branch. But it's indeed not resolved in the 0.0.45 release. I'll maybe push a new release to include all the bug fixes concerning Shaarli 0.0.45.

Concerning the replacement of type="submit" by type="button", it's not possible as Shaarli expects a POST request for both cancellation and deletion as well. I could of course do it via Javascript but it wouldn't make sense here.
