### ISSUE TITLE
Favicon issue

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#16]
I'm using the latest update and there are changes about the favicon.
How can I use my own favicon to work on every devices?

It could be a good idea to add a button somewhere in the options menu to add our own favicon.

Thanks.

**Comment by kalvn** [comment]
I used [this tool](http://www.favicon-generator.org/) which should enable you to generate the exact same icons as I did in the last commit. There is also [this tool](http://realfavicongenerator.net/) which can help you.
Concerning the button to add your own favicon, it's not something I can do in a theme. You should suggest this idea directly on the official Shaarli repository.
