### ISSUE TITLE
html encoding issue

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#17]
Hi kalvn ,
when I'm editing a link, shaarli is showing the html encoding code:
![screenshot - 15092015 - 12 40 19](https://cloud.githubusercontent.com/assets/1882534/9875426/311dd504-5bae-11e5-984d-8bd91f695a05.png)

Moreover, when I'm adding a link like https://budgetparticipatif.paris.fr/bp/jsp/site/Portal.jsp?document_id=1959&portlet_id=123.
`&` gets encoded into `&amp;`. And it gets saved with the badly encoded form.

I'm having the problem since a long time actually.
Of course it might be a problem on my side.
I'm using last version (master) of shaarli community and of your theme.

Thanks
J.

**Comment by kalvn** [comment]
For more information, see my comment here: https://github.com/shaarli/Shaarli/issues/352#issuecomment-140360056

Thanks for the feedback, jeekajoo.

**Comment by jeekajoo** [comment]
Looks like you fixed it with https://github.com/kalvn/Shaarli-Material/commit/10f77f3df928a1977a138a3bf2a1cac267351077
This is great. Thanks
