### ISSUE TITLE
Shaarli 0.6.0?

### ISSUE THREAD

**Issue by ParoTheParrot** [kalvn/Shaarli-Material#18]
Everything adopted from https://github.com/shaarli/Shaarli/releases/tag/v0.6.0? 
Can I use Shaarli-Material for Shaarli 0.6.0?

**Comment by kalvn** [comment]
Nothing was done for Shaarli 0.6.0 yet but I'll work on it today.

**Comment by kalvn** [comment]
I just finished the first testable version which lives in a separate branch for now: https://github.com/kalvn/Shaarli-Material/tree/v6

I tested all plugins available for now and they work well although some of them look weird because of the style or the icons used.

Don't hesitate to give me your feedback if you find bugs or strange behaviors.

**Comment by NerosTie** [comment]
Can we update to shaarli 0.6 without serious issues with the theme?

**Comment by kalvn** [comment]
Yes, I tested everything I could and found no issue so it should be safe. As always, backup your files before updating, just in case.
For now, the version compatible with Shaarli 0.6 lives in a separate branch. I wait a few days to ensure there is no major bug and then I'll deploy it on the master branch.

**Comment by ParoTheParrot** [comment]
Shaarli-Material-6 feels good - thanks!

**Comment by ParoTheParrot** [comment]
.. 0.6.1 is out!

**Comment by kalvn** [comment]
Yep, I'll upgrade the theme soon but according to the changelog, it should already work.

**Comment by nicolasdanelon** [comment]
I'm currently running the theme in shaarli 0.6.1 works great.
![screen shot 2015-12-04 at 16 25 12](https://cloud.githubusercontent.com/assets/2846046/11599090/a273eb7e-9aa3-11e5-9c31-41de38242613.png)
![screen shot 2015-12-04 at 16 25 03](https://cloud.githubusercontent.com/assets/2846046/11599092/a2799d6c-9aa3-11e5-8231-407eeb7ab671.png)
![screen shot 2015-12-04 at 16 24 58](https://cloud.githubusercontent.com/assets/2846046/11599091/a27461bc-9aa3-11e5-95bb-aff770d7b07e.png)
![screen shot 2015-12-04 at 16 24 56](https://cloud.githubusercontent.com/assets/2846046/11599093/a27c37ca-9aa3-11e5-90a6-6fc46a924fc6.png)

**Comment by kalvn** [comment]
Thanks for the feedback. There was an issue with the footer which was displaying an inexistent variable error but I fixed it. I also moved the changes to the master branch and did a release package for the version 0.6.1. Therefore, I close the ticket.
