### ISSUE TITLE
Missing Title when logged

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#2]
When logged the title is missing for a permalink page.

**Comment by kalvn** [comment]
Thanks for this feedback.
This problem comes from Shaarli directly, not from this theme.

I will open an issue on the Shaarli project.

**Comment by NerosTie** [comment]
Thank you!

Really great theme btw! It should be the new default theme for shaarli :)

**Comment by kalvn** [comment]
Thanks, I really appreciate :)

[Here is the ticket I opened](https://github.com/shaarli/Shaarli/issues/175). The fix is planned for version 0.9beta so it'll hopefully be quite soon.

**Comment by kalvn** [comment]
The following commit fixes this on the official repo: https://github.com/shaarli/Shaarli/pull/190
