### ISSUE TITLE
A wave effect on buttons/icons

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#20]
In every material design things I see, there is a "wave effect" on icons and buttons.

(here, an example of what I'm talking about: http://www.cssscript.com/demo/google-material-design-ripple-effects-with-wave-js/)

I think it could be a nice thing to add to this theme (specially for the red "+" button)

**Comment by kalvn** [comment]
I already thought about it in the past but I wanted the theme to stay very simple and clean.
Then I may consider adding this as an optionnal setting. I'll think about it and update this ticket soon.

**Comment by NerosTie** [comment]
Thanks! But why an optional setting?

**Comment by kalvn** [comment]
Because some users might find this heavy in terms of Javascript.
I did a first version that I tried to keep light and clean, you can test it via this commit: https://github.com/kalvn/Shaarli-Material/commit/0106a5cc7eb7248882e939e80a559db4556b9422

**Comment by NerosTie** [comment]
It really needs JS? It's not possible with CSS?

**Comment by kalvn** [comment]
You cannot have something close enough to the original one provided by Google with just CSS, no.

**Comment by NerosTie** [comment]
Thanks!
