### ISSUE TITLE
Edit a link - page size

### ISSUE THREAD

**Issue by wouaibe** [kalvn/Shaarli-Material#22]
Evolution
Define the same page size between  "link" view and "Edit a link" view.
Could you please increase the width of "Edit a link" page to be close the links view page ?

**Comment by kalvn** [comment]
Any reason for this?
I feel like it would be a bit too wide. If you want to write long descriptions, you can already make the text area taller.
If you really want to enlarge the edit text page, you can make the following change:
In the `material/editlink.html` file, change the line `16`:
```html
<div class="col-md-6 col-md-offset-3">
```

into 

```html
<div class="col-md-12">
```

**Comment by wouaibe** [comment]
Yes !
In the shaarli original theme, the editlink is larger so it is easier to write long descriptions.
I have done your proposal of change : for me it is OK :-)
It works fine on my 5'' phone, 7'' tablet and 17'' PC !
Thanks'

**Comment by kalvn** [comment]
I just published an update which offers the possibility to increase the width of the link edition page. You could be interested :)

**Comment by wouaibe** [comment]
Good !
Thanks
