### ISSUE TITLE
_blank option

### ISSUE THREAD

**Issue by wouaibe** [kalvn/Shaarli-Material#23]
Evolution
Add a 'target="_blank"' option for link list on Tools/configuration of shaarli
So that on linklist page, each link opens in new tab.

**Comment by kalvn** [comment]
This change needs to be done on Shaarli itself. As a theme developer, I cannot add a setting by myself. You can open an issue on the official Shaarli repository: https://github.com/shaarli/Shaarli/issues

**Comment by wouaibe** [comment]
Done !
https://github.com/shaarli/Shaarli/issues/422
