### ISSUE TITLE
lightbox + pluginadmin

### ISSUE THREAD

**Issue by nicolasdanelon** [kalvn/Shaarli-Material#25]
what about add a lightbox for deleting publication process?
and the plugin admin ui ? any release date ?

again. thanks for this awesome, incredible and wonderful theme!

**Comment by kalvn** [comment]
I'm working on UI improvements which may include such lightbox system. I'll consider it.
Concerning the plugin admin panel, it's almost ready. It's coming in the next few days :)

**Comment by nicolasdanelon** [comment]
wooohoo !

**Comment by kalvn** [comment]
I just released the last version including the plugin admin. I'll wait a little for feedbacks before making the release so feel free to deeply test it :)

The release also includes:

- ripple effect on the logo
- possibility to hide the search overlay with ESC key
- click on the search field hides autocomplete
- debug option has been removed as the last version of Shaarli seems to automatically remove it from the config file

As always, even if there shouldn't be any issue, do a backup of your data before testing it.

**Comment by jeekajoo** [comment]
looks good to me :)
thank you!

**Comment by nicolasdanelon** [comment]
works awesome, firefox, chrome & IE11 and edge. We have some issues with the right nav in IE9 but.. how cares!? :+1:

**Comment by kalvn** [comment]
Thanks for the feedback!
I have to admit that IE versions lower than 11 are clearly out of scope :)
