### ISSUE TITLE
Problèmes d'affichage

### ISSUE THREAD

**Issue by iGormilhit** [kalvn/Shaarli-Material#33]
I'm using the master branch of shaarli community and your theme. I've upgraded shaarli, and your theme. But I encountered some display problems.

Here is how it looks like with a local install. I tried with different browser. It was the same problem on the server installation ( https://id-libre.org/shaarli ), but for this one I went back to the default theme.

![selection_420](https://cloud.githubusercontent.com/assets/1557213/13346837/8d3dfb02-dc69-11e5-8766-26a29dd2e78d.png)

I've disabled the plugins I was using (qrcode), but that wasn't the problem. The funny thing is that when I downgraded to the previous versions of the theme, the problem was still there, even after removing the cache of the browser.

Of course I will give you all the missing details, you can ask ! :)

**Comment by iGormilhit** [comment]
I should have thought of it before : I tried to start from a fresh install of shaarli and your theme, reimport the data, and everything is working fine. Sorry.

**Comment by kalvn** [comment]
No problem ;)
Based on the screenshot, it looks like your version of Shaarli Material was not the last one (based on the presence of search and filter buttons) so yep, a fresh install is what I would have recommended. I'm glad it works now.

**Comment by kalvn** [comment]
By the way you could disable the qrcode plugin as Shaarli Material still includes it's own way of generating qrcodes for now (via the bottom right icon).

**Comment by iGormilhit** [comment]
That's right, it's even better like this ! Thank you.
