### ISSUE TITLE
Color header in chrome (android)

### ISSUE THREAD

**Issue by nicolasdanelon** [kalvn/Shaarli-Material#34]
This is not difficult in a "normal website" what about shaarli?

http://stackoverflow.com/a/26960753

**Comment by kalvn** [comment]
All in all, Shaarli is a website as well so no it won't be difficult :)
Thanks for the idea, I'll do it soon!

**Comment by kalvn** [comment]
Done. https://github.com/kalvn/Shaarli-Material/commit/cc568a710bbfd6b976b96eabde30775f9bfeaad9

If you use the color customization of Shaarli Material, it should use it. Otherwise, it'll use the default blue.

**Comment by nicolasdanelon** [comment]
:+1: great
