### ISSUE TITLE
"Are you sure you want to delete this link ?" modal not poping in "post" screen

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#38]
How to reproduce: 

* Shaarlink something
* Reshaarlink same link using bookmarklet. The previously saved shaarlink should open in the "post" screen, in a window. Now try to delete the shaarlink with the button. Nothing happens.

Expected behaviour:

A modal appears. `Are you sure you want to delete this link ?` Yes / No

Thanks

**Comment by kalvn** [comment]
Thanks a lot for the feedback.

This commit https://github.com/kalvn/Shaarli-Material/commit/74c9908f39acea4b3f78258b4dd307441f09f1ab should fix the issue. I also updated the release v0.6.5.

**Comment by jeekajoo** [comment]
fixed. thanks :+1:
