### ISSUE TITLE
hide (+) button while editing a shaarlink

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#4]
Hi,
it happened to me several times to unintentionally click the (+)* button while trying to hit 'save' button while editing a shaarlink. Result is that you lose all the text you entered :-S

Do you think we could hide this button in this situation?

Thanks
J

\* the button to add a shaarlink

edit: it is especially true on mobile where (+) button is overlapping with 'save' button.

**Comment by kalvn** [comment]
You're right this link can be a problem on several pages depending on the screen size. And as it's almost useless elsewhere than on the home page, I removed it from almost all other pages.

It's in the last commit: https://github.com/kalvn/Shaarli-Material/commit/f6b029f8b907df18e60f5054e4f6f19f24c40d7d
So you can take the current master version to apply this change. The only modified file is `material/page.header.html`.

**Comment by jeekajoo** [comment]
thanks kalvn :+1:
