### ISSUE TITLE
Le formulaire de soumission est parfois « cassé »

### ISSUE THREAD

**Issue by jlnbdt** [kalvn/Shaarli-Material#40]
Bonjour,

Je suis tombé sur deux pages qui « cassent » le formulaire de soumission lorsque je tente de les ajouter à mon Shaarli : 

- http://www.eurohex.eu/
- http://freakonometrics.hypotheses.org/9069

J'ai essayé de les enregistrer avec le thème de base (via le site de démo), le problème ne se pose pas. J'en conclus (peut-être à tort) qu'il s'agit d'un bug de ce thème, que j'utilise. 

Merci :)

**Comment by ArthurHoaro** [comment]
Probablement shaarli/Shaarli#512.

**Comment by kalvn** [comment]
Yep, je confirme que depuis que cette Pull Request a été mergée le problème est réglé. Je t'invite donc à mettre à jour ton Shaarli @jlnbdt
Merci pour l'investigation @ArthurHoaro
