### ISSUE TITLE
2 clicks needed to login or logout

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#41]
Hi,

Would it be possible to be just 1 click away from login and logout? Today we need 2:
- 1 for displaying a submenu
- 1 for actually log in/out

For this, I guess we need to have 1 icon for login that changes into another icon for logout.

Thanks
J.

**Comment by kalvn** [comment]
I agree, that's what I thought when I did it but at that moment I wasn't able to find an icon eloquent enough. I'll think about this and maybe improve tooltips to make it clearer.

**Comment by kalvn** [comment]
The implementation has been done in the last commits of the master branch.

**Comment by jeekajoo** [comment]
Perfect.

Thank you @kalvn !
