### ISSUE TITLE
make fonts bigger

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#42]
Hi,

Visitors have to zoom in to read the text: https://lut.im/xgJWO1pe5h/WkaJhpEpMJhKDkTj.png
I think it would be better to increase the font size generally.

https://www.smashingmagazine.com/2011/10/16-pixels-body-copy-anything-less-costly-mistake/

Thanks 
J.

**Comment by kalvn** [comment]
Interesting article, thanks. I'll do a few tests with a small increase of the base font size.

**Comment by iGormilhit** [comment]
I do agree with @jeekajoo and I add another interesting article on that subject : http://xtianmiller.com/notes/your-body-text-is-too-small/ (found through https://www.quaternum.net//2016/10/05/enlarge-your-body-text-size/ )

**Comment by kalvn** [comment]
I definitely agree on this, I just lack time lately but I'll work on this as soon as I can (as well as other minor changes).

**Comment by jeekajoo** [comment]
Thank you.
