### ISSUE TITLE
Arrow out of bounds

### ISSUE THREAD

**Issue by nicolasdanelon** [kalvn/Shaarli-Material#43]
when we see both pager arrows ... the one on the right (newer) is out of boundaries creating a little right margin :(

![screen shot 2016-03-30 at 17 18 15](https://cloud.githubusercontent.com/assets/2846046/14156215/a1beb462-f69b-11e5-8b34-a1f1a5bb2409.png)
![screen shot 2016-03-30 at 17 18 06](https://cloud.githubusercontent.com/assets/2846046/14156214/a1beab2a-f69b-11e5-8977-432514bde86a.png)

**Comment by kalvn** [comment]
Indeed. The last commit (https://github.com/kalvn/Shaarli-Material/commit/0466cb41337417adb05d4c3d963e070caf4d9789) fixes this by reducing the "page" label on very small screens and increasing the space dedicated to arrows.
Thanks for the feedback.

**Comment by nicolasdanelon** [comment]
hahahahahahaha I create this issue before of the commit ! 
good job, as usual ! :+1:
