### ISSUE TITLE
tag cloud links font size is broken using shaarli master

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#44]
Hi,

Maybe I'm anticipating too much
At least, it is here for reference: https://github.com/shaarli/Shaarli/pull/527

Thanks
J.

**Comment by kalvn** [comment]
Thanks for the reference. I'll wait a little to give people time to upgrade their Shaarli before.

**Comment by jeekajoo** [comment]
Yep no problem.
Note: For people using shaarli master like me, here is the fix you need to apply to the template
```diff
diff --git a/material/tagcloud.html b/material/tagcloud.html
index 52ccafd..1e02a0a 100644
--- a/material/tagcloud.html
+++ b/material/tagcloud.html
@@ -11,7 +11,7 @@
     </div>
     <div id="cloudtag">
         {loop="tags"}
-        <span class="count">{$value.count}</span><a href="?searchtags={$key|urlencode}" style="font-size:{$value.size}pt;">{$key}</a>
+        <span class="count">{$value.count}</span><a href="?searchtags={$key|urlencode}" style="font-size:{$value.size}em;">{$key}</a>
         {/loop}
     </div>
     <div id="plugin_zone_end_tagcloud" class="plugin_zone">
```

**Comment by kalvn** [comment]
It's done. I'll assume people who use the master version of the theme use the master version of Shaarli and update both at the same time :)
