### ISSUE TITLE
Plugin administration is not well reloaded

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#46]
How to reproduce:

1. Go to Plugin administration
2. Enable or disable a plugin
3. Click on "save plugins"
= the page is reloaded but it's the same configuration as before =
4. Manually reload a second time the page
= it's ok =

**Comment by ArthurHoaro** [comment]
That's related to Shaarli. @alexisju experienced it, but our investigations didn't lead us anywhere.

**Comment by kalvn** [comment]
Yes, I had the same problem when I was developing on Ubuntu 14.
Strangely, it works properly when developing on Windows. And it works well on my server (hosted by OVH).
I close the issue and let you open another one on the official Shaarli repo (or check if it doesn't already exist).
