### ISSUE TITLE
Unable to disable qrcode plugin

### ISSUE THREAD

**Issue by wouaibe** [kalvn/Shaarli-Material#48]
In admin page, it is impossible to disable the qrcode plugin. It appears always.
It seems to come from theme
See [https://github.com/shaarli/Shaarli/issues/581](https://github.com/shaarli/Shaarli/issues/581)

**Comment by kalvn** [comment]
When you say it's impossible to disable the QR Code, do you mean it keeps being checked even though you unchecked it and submitted the plugins administration form? Or you mean that the QR Code still appears in links despite the fact that you disabled it?

If you talk about the second case, do you use the last version of the theme (0.7.0)? I recently added a better management of this QR Code plugin so updating to the last version could solve your issue.

If you talk about the first case, it may be related to issue https://github.com/kalvn/Shaarli-Material/issues/46 which is itself linked to a Shaarli issue that is not yet solved.

**Comment by wouaibe** [comment]
Second case.
In doubt, i have made a update.
Here : 
[Result with plugin activated in admin form](http://s33.postimg.org/pfg1uaxvj/avecqrcode.png)
[Result with plugin dissabled in admin form](http://s33.postimg.org/79prueb5r/sansqrcode.png)

**Comment by kalvn** [comment]
An upgrade of the theme will definitely solve this.
