### ISSUE TITLE
The daily page is broken on mobile

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#49]
![screenshot_2016-05-27-19-47-39_com android chrome](https://cloud.githubusercontent.com/assets/4572452/15616465/34933396-2444-11e6-8d13-440842129f6c.png)

As you can see, the "Daily" page is really broken on mobile. This issue concerns the default theme as well but is it possible to change that in your theme? Plus, this page is not really "material".

**Comment by kalvn** [comment]
Indeed I should have worked on this page long time ago. When I created the theme, I wanted to keep it as is because I liked the "newspaper" style and it make sense ("Daily" evokes newspaper).

But it's time to find a new design for this page, I'll think about something :)

**Comment by nicolasdanelon** [comment]
What about something like this app ?
https://play.google.com/store/apps/details?id=com.google.android.apps.magazines&hl=en

**Comment by NerosTie** [comment]
Any news? ;)

**Comment by kalvn** [comment]
Working on it, slowly but surely :)

I preferred prioritize the support of Shaarli 9.1.

**Comment by NerosTie** [comment]
You mean Shaarli 9.2? ;)

**Comment by kalvn** [comment]
Damn your right, I just noticed that 0.9.2 was out.

**Comment by kalvn** [comment]
This should finally be okay now :)

**Comment by NerosTie** [comment]
Nice, thanks!
