### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by k0nsl** [kalvn/Shaarli-Material#51]
I just wanted to let you  know I really appreciate this project by you. I have only done a few tweaks here and there,.
You can see my copy running on following site:
https://bookmarks.k0nsl.org

Have a good weekend,

**Comment by kalvn** [comment]
Thank you very much, I appreciate :)

Your tweaks look indeed quite discreet but I'm glad you hacked the theme to better fit your needs.

If there is anything else you'd need help for, feel free to ask.
