### ISSUE TITLE
shaarli title missing

### ISSUE THREAD

**Issue by mro** [kalvn/Shaarli-Material#53]
Material: v0.7.0 
shaarli: https://github.com/shaarli/Shaarli/commit/b6e58bab8a7 (which is current master)

Seen via https://travis-ci.org/mro/Shaarli-API-test/builds/145849752 and manual, fresh installation.

    $ fgrep '"title":'  data/config.json.php 

doesn't display top left but rather just "Shaarli". Not sure if it's a template or core issue, but I suspect the template because https://travis-ci.org/mro/Shaarli-API-test/builds/131254883 succeeds (without material template)

**Comment by mro** [comment]
core issue: https://github.com/shaarli/Shaarli/issues/600

**Comment by mro** [comment]
OT: @kalvn @nodiscc you're sharing a room?

**Comment by nodiscc** [comment]
what nope

**Comment by mro** [comment]
github profile locations localhost and 127.0.0.1 :-)

**Comment by kalvn** [comment]
Each of us is on its internal network, that's all :)
