### ISSUE TITLE
Typo in tools.html

### ISSUE THREAD

**Issue by ArthurHoaro** [kalvn/Shaarli-Material#54]
![http://i.imgur.com/80g7wab.png](http://i.imgur.com/80g7wab.png)

bookmarklets

**Comment by kalvn** [comment]
Can't believe I didn't see it before. Thanks for the feedback.

**Comment by ArthurHoaro** [comment]
You're welcome. It looks nice BTW. :)

**Comment by kalvn** [comment]
Thanks :)
Fixed via https://github.com/kalvn/Shaarli-Material/commit/b3bdc571310ee11b3a656b98d3a13c78220f0179
