### ISSUE TITLE
Page goes black on enabling template

### ISSUE THREAD

**Issue by Gabbalo** [kalvn/Shaarli-Material#55]
Hi there,

after installing the template (material folder with 'tpl/material/' in config.php or whole repo with 'tpl/Shaarli-Material/material/' does not matter, effect is the same.
The new favicon shows up, nothing else. Page is going blank. 
Returning to the original GLOBAL in config.php fixes the problem ... without using the nice, new template, of course.
I am currently using Shaarli 0.6.5 with the newest download of the material template. 
Did I oversee anything? 

Greetzs, Gabbalo

**Comment by kalvn** [comment]
Hey,
The version of Shaarli and Shaarli Material must be the same. If you use [Shaarli 0.6.5](https://github.com/shaarli/Shaarli/releases/tag/v0.6.5), you must install [Shaarli Material 0.6.5](https://github.com/kalvn/Shaarli-material/releases/tag/v0.6.5). And therefore, you must use [this README file to configure it](https://github.com/kalvn/Shaarli-Material/blob/v0.6.5/README.md).

But I suggest that you use the last stable version of both: the v0.7.0.

**Comment by kalvn** [comment]
Feel free to close the issue if it now works as expected.

**Comment by Gabbalo** [comment]
I will test it tomorrow evening (UTC+1) and if it will work, which I expect, I will of course close this Layer 8 issue :)
Please be patient until then and thank you for the fast reply.

**Comment by kalvn** [comment]
Hey Gabbalo, any news on this issue?

**Comment by Gabbalo** [comment]
I am so sorry I forgot about this issue. I am quite busy these days.
Of course it worked just fine so I am closing it.
Thanks again an horray to your commendable issue tracking :)
