### ISSUE TITLE
Inspiration from MyFrama for the daily view.

### ISSUE THREAD

**Issue by iGormilhit** [kalvn/Shaarli-Material#58]
I don't use the daily view, so it's not very important. But I find that the MyFrama theme is a good inspiration for that page:
![selection_171](https://cloud.githubusercontent.com/assets/1557213/20047456/c802e00e-a4b4-11e6-8dc0-78a6ee9561a9.png)

**Comment by kalvn** [comment]
Indeed that's close to what I'd like to achieve. However, I find it a bit too "loaded" with those strong shadows and large card footers. But I like how blocks are organized.

And it would allow to finally make it responsive (https://github.com/kalvn/Shaarli-Material/issues/49).

I'll have a look on this.

**Comment by iGormilhit** [comment]
You're right about the shadows and cards footers. In fact, that's indeed the blocks organisation that appealed me...

**Comment by kalvn** [comment]
The Daily Shaarli page was just updated, partly based on your suggestion :)
