### ISSUE TITLE
No pages navigation at last page

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#6]
If I reach the last page of my Shaarli (which has more than 1 page), the navigations buttons disapear.

**Comment by kalvn** [comment]
That's perfectly true, the last commit ( https://github.com/kalvn/Shaarli-Material/commit/e13fca7aef54e36642134d4efa271bdfd428c111 ) fixes the issue.
Thanks for the repport.

**Comment by NerosTie** [comment]
Thanks!
