### ISSUE TITLE
Support for the v0.8.1

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#63]
Your theme is not compatible with the latest version of Shaarli (permalinks are broken and maybe some other things). Can you do something about that? Thanks!

**Comment by kalvn** [comment]
Yes that's absolutely true. I'll take care of it as soon as possible. Most likely this week or next week.

**Comment by nicolasdanelon** [comment]
thanks kalvn !

**Comment by kalvn** [comment]
[This release](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.8.1) should fix these issues :)

As always, do a backup of your installation before deploying this update.

Feel free to open new issues if you discover problems.

**Comment by NerosTie** [comment]
It was really fast! Thanks!

**Comment by ArthurHoaro** [comment]
Awesome! For people who stumble on this thread and for your release description @kalvn, I've released sooner today v0.8.2 to fix a major issue, but it doesn't affect templates.

**Comment by kalvn** [comment]
Thanks for the notice.
