### ISSUE TITLE
Typo in linklist.html

### ISSUE THREAD

**Issue by dajare** [kalvn/Shaarli-Material#69]
There is a small typo in [the summary under the "link list"][s] (`linklist.html`, line 137):

> 5 links, including 1 privates

The last word should either be "private" (no "s"), or (better?) "private links" -- but then there would need to be some logic to add an "s" or not to "link" depending on the number. If there are 0 or >= 2, then an "s" is needed, but no "s" if there is only 1. Would this do it?

```
 <em>{$linkcount} links{if="!empty($privateLinkcount)"}, including {$privateLinkcount} private link{if="$privateLinkcount!=1"}s{/if}{/if}</em>
```

I've never used RainTPL before, so I don't know if my `!=1` syntax is correct. But something like that would fix the English. It should produce:

> 5 links, including 1 private link

Or, since the logic is already excluding the phrase if there are no (0) private links, then the syntax could be: `{if="$privateLinkcount>1"}s{/if}` to get the desired result.

*Otherwise* if it is just 

> 5 links, including 1 private

Then there should *never* be an "s" at the end, and no "logic" at all is required in that case. :)

[s]: https://github.com/kalvn/Shaarli-Material/blob/d2db7bb45be6c74315ea8ef6c15a22b2d833b27d/material/linklist.html#L137 "Link to line in source"

**Comment by kalvn** [comment]
I chose the second option https://github.com/kalvn/Shaarli-Material/commit/1aae170b70085e731d2972dce62123db244c480a

Thanks a lot for reporting this :)

**Comment by dajare** [comment]
Hmmm - on upgrading Shararli to 0.9.3, and Material to latest, I see this tiny (really tiny!) niggle is still present. Now it is in [line 143 of `linklist.html`][1]:

        <em>{$linkcount} link{if="$privateLinkcount > 1"}s{/if}{if="!empty($privateLinkcount)"}, including {$privateLinkcount} private{/if}</em>

Should be:

        <em>{$linkcount} link{if="$linkcount > 1"}s{/if}{if="!empty($privateLinkcount)"}, including {$privateLinkcount} private{/if}</em>

with the change in the first `{if=...` statement.

Hope that helps!

[1]: https://github.com/kalvn/Shaarli-Material/blob/17dd870c44cd8e89fff7668411b5665a37469b74/material/linklist.html#L143

**Comment by kalvn** [comment]
You are totally right, that's now fixed https://github.com/kalvn/Shaarli-Material/commit/56f43248664742b9720045d00dafeea9d9223400

Thanks! :)
