### ISSUE TITLE
no thumbnail displayed when description is empty

### ISSUE THREAD

**Issue by nlegaillart** [kalvn/Shaarli-Material#7]
Hi Kalvn,

I noticed that if there's no description for a given link, no image was displayed, even if there was a generated thumbnail on disk.

To get the thumbnails with or without description, I had to change the condition on line 55:
{if="$value.description|thumbnail"}

Hope it's a bug and not a feature ;)

Regards,
nico

**Comment by kalvn** [comment]
It was a bit more tricky than the fix you proposed but I figured out a way to solve this. It's available in the last commit ( https://github.com/kalvn/Shaarli-Material/commit/6f69710a6359c435e80dbb51f381427e8397413d ).

So yep it was definitely a bug, thanks for the report :)
