### ISSUE TITLE
Support for v0.9.0

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#70]
What is the compatibility of the theme with this version?

**Comment by nicolasdanelon** [comment]
works fine for me

**Comment by kalvn** [comment]
I didn't have time yet to do a full testing session but so far I didn't find any problem. You just need to use the very last master version.

**Comment by plexa** [comment]
@kalvn Are you aware that delete does not work?

**Comment by kalvn** [comment]
@plexa It works properly on my side. Can you describe precisely how to reproduce your issue? Does deletion work with the default Shaarli theme?

**Comment by plexa** [comment]
@kalvn If I stay with the (new) default theme all the usual actions work fine, but after switching to "material" the theme lacks of this functions:
* delete does not work (adding and editing Link works fine)
* in CONFIGURATION the timezone has no values / nothing to select.
* in CONFIGURATION there is no themechooser

Installed Software: shaarli v. 0.9.0 with Shaarli-Material-master (v.0.8.3)

**Comment by kalvn** [comment]
I confirm that it works for me. I did the following:

1. I downloaded Shaarli (master) from Git
2. I downloaded Shaarli Material (master) from Git and copied the folder *material* into *tpl/*
3. I launched the local web server and did the configuration with the default theme
4. I went into *Tools > Configure your Shaarli* to switch to *Material* theme

And I was perfectly able to delete links, change the timezone or the theme.

I think you don't use the very last master version of the theme. If you downloaded v0.8.3, it's already too old and doesn't contain last fixes to make the theme work with Shaarli v0.9.0. The version v0.9.0 will come soon when I'm sure there is no issue anymore.

**Comment by aurmil** [comment]
hello
just to say I had the same problem with Material for 0.8.3 and Shaarli 0.9.0
replacing with Material master branch is OK
thanks

**Comment by kalvn** [comment]
@aurmil this is absolutely normal. Shaarli Material must only be used with an equivalent version of Shaarli. Meaning that if you want to use Shaarli v0.9, you must wait for me to release Shaarli Material v0.9. I know it can be frustrating to wait but when a new version of Shaarli is released, it requires time for me to adapt the theme so that it works properly.

An alternative is to use Master version of both Shaarli and the theme but it's risky as it contains very last developments which could contain bugs.

**Comment by kalvn** [comment]
I just published release v0.9.0 https://github.com/kalvn/Shaarli-Material/releases/tag/v0.9.0

**Comment by NerosTie** [comment]
Thanks!
