### ISSUE TITLE
Tag cloud boken on 0.9.0

### ISSUE THREAD

**Issue by Gabbalo** [kalvn/Shaarli-Material#71]
When using this theme, a click on "Tag cloud" will present you with a http error 500. When changing the theme back to default, evething is working just fine. 
So there might be a problem with the theme when using the current (2017-08-04) version of shaarli.

**Comment by kalvn** [comment]
I'll have a loot. But please keep in mind that there is no guarantees for Shaarli Material to work with the last version of Shaarli. Only releases are built to work properly with similar version numbers.

**Comment by nicolasdanelon** [comment]
# Compatibility
## Shaarli Material was tested and validated on Shaarli 0.8.3.
![alt text](http://i0.kym-cdn.com/photos/images/newsfeed/000/096/044/trollface.jpg?1296494117)

**Comment by kalvn** [comment]
Actually this is a mistake, Shaarli Material was tested with Shaarli v0.9.0, but the current master branch of Shaarli is obviously not v0.9.0.

**Comment by nicolasdanelon** [comment]
please update the readme file tho

**Comment by kalvn** [comment]
Done.

Actually @Gabbalo if you use the tags branch it works fine: https://github.com/kalvn/Shaarli-Material/tree/tags but it's still a work in progress so the rest of tags pages are not finished yet. Therefore I highly suggest **not**  to use this page in production.

**Comment by kalvn** [comment]
I now close this issue as I merged most of tags related developments in the master branch. The 9.1 is coming soon :)
