### ISSUE TITLE
Material 0.9.1 - toolbar icons now missing

### ISSUE THREAD

**Issue by dajare** [kalvn/Shaarli-Material#72]
Having just updated to Material to 0.9.0 (which worked great), I have now applied the 0.9.1 update. As a result, the toolbar icons have gone missing, as seen here:

![screenshot][gif]

(That's actually an [animated gif][gifv] -- the pic above is static.) My Shaarli itself is 0.9.2. I'm happy to help debug if some instructions are provided. 

[gif]: https://i.imgur.com/pY7GZL6.gif
[gifv]: https://i.imgur.com/pY7GZL6.gifv

**Comment by kalvn** [comment]
It's probably linked to the icon font which doesn't load properly. Can you open devtools (F12) and check the console so see if you have any error message? It could also be linked to a browser extension which may block non-standard fonts.

**Comment by dajare** [comment]
Here's a screenshot of the network downloads from Chrome. You can see the icons that it is stalling on. (At least it gets two! In Firefox I don't get any.)

![material-icon-prob](https://user-images.githubusercontent.com/40625/31317500-0658bab2-ac3a-11e7-9a5d-cfff822b4d98.jpg)

Any thoughts?

**Comment by kalvn** [comment]
Looks like a cache issue. Your browser tries to download icon that are not present anymore since they have been replaced by the font (example: tools.png, key.png, etc.).

Can you try to clear your browser's cache?

**Comment by dajare** [comment]
> Can you try to clear your browser's cache?

I tried that - no change. I also tried two browsers on this machine that had not visited the site before (Chromium and Safari -- no toolbar icons), and from another machine that had not visited the site (no icons).

Is there something else I can check?

**Comment by kalvn** [comment]
It strange, it looks like you only updated CSS and JS but not HTML templates. For exemple, the toolbar login button should look like that:
![image](https://user-images.githubusercontent.com/6149640/31317799-97153dc0-ac47-11e7-852f-6dfc84dea367.png)

But in your case you still have the old template:
![image](https://user-images.githubusercontent.com/6149640/31317804-af1c8bda-ac47-11e7-9017-08d7663f8ae8.png)

There is maybe a flat file cache on your server side but I can't help with that.

**Comment by dajare** [comment]
Thanks so much for looking around -- that was a help. I just got a fresh master.zip, uploaded and installed it (instead of the release version) and now all is well. I'm still puzzled why it didn't work before (I always upload the zip and "expand" on the remote site) but all good now!

Shaarli + Shaarli-Material = 👍  :)
