### ISSUE TITLE
Consistent interface

### ISSUE THREAD

**Issue by ivangretsky** [kalvn/Shaarli-Material#73]
Good day!
Thank you for a nice theme!

I reaally like how it looks on the main page, but picture wall and daily pages have very different design. Is it possible to make it all straight via some kind of config? I would prefer it all pure material (know its just some personal prefs, but I imagine this would be pretty common one).

**Comment by kalvn** [comment]
Hi there. The redesign of those pages is planned and also tracked on issue https://github.com/kalvn/Shaarli-Material/issues/49 but I preferred prioritizing the support of new Shaarli version so I didn't have so much time to spend on it. But it'll definitely come in a near future :)

**Comment by ivangretsky** [comment]
Good to know that, thanks!

**Comment by kalvn** [comment]
The Daily Shaarli was just updated. I'll now see what I can do for the picture wall.

**Comment by poVoq** [comment]
Any chance to allow customization of the Daily Shaarli? Like a custom name and font etc.?

Also would be a card view like this:
https://github.com/dhoko/ShaarliTemplate
be possible as an option?

Thanks!

**Comment by kalvn** [comment]
@poVoq you can create the file *data/user.css* and customize anything you'd like. You just need to know a bit of CSS.

Concerning the card view, I find it okay for the Daily view because it fits the newspaper aspect but I find it a bit too messy for the main view.

**Comment by poVoq** [comment]
Thanks for the reply. I agree, card view might not be for everyone... but as an option it would be nice.

Is there an up to date skeleton code for the user.css somewhere? I shortly checked yesterday, but I only found options for very old versions of Shaarli.

**Comment by kalvn** [comment]
Actually by default, user.css is empty. Up to you to put whatever CSS code you want.

For example, [Liandri](https://shaar.libox.fr) did that: https://shaar.libox.fr/data/user.css

**Comment by poVoq** [comment]
Can I somehow re-enable that "external link" font awesome icon in front of the title that is visible in the default theme? That would make it much more obvious to users where to click to go to the original article.

**Comment by kalvn** [comment]
This CSS in *user.css* should work:

```css
a.link-title:before {
    content: "\F3CC";
    font-family: Material;
}
```
