### ISSUE TITLE
Variable in includes.html

### ISSUE THREAD

**Issue by gruenheit** [kalvn/Shaarli-Material#75]
Hi kalvn,
since I installed your theme today I tried to track down the source of the meta header

`<meta name="theme-color" content="#2196f3"> `

Although I configured "MATERIAL_COLOR": "#669900" in data/config.json.php as in ([Customization](https://github.com/kalvn/Shaarli-Material#customization))! I found this in includes.html

```
{if="$conf->get('config.THEME_COLOR')"}
{$themeColor=$conf->get('config.THEME_COLOR')}
<meta name="theme-color" content="{$themeColor}">
{else}
<meta name="theme-color" content="#2196f3">
{/if}
```

It works as intended when I change it to 

```
{if="$conf->get('config.MATERIAL_COLOR')"}
{$themeColor=$conf->get('config.MATERIAL_COLOR')}
<meta name="theme-color" content="{$themeColor}">
{else}
<meta name="theme-color" content="#2196f3">
{/if}
```
kind regards,
Christian

**Comment by kalvn** [comment]
That's a mistake, variable `THEME_COLOR` should indeed be `MATERIAL_COLOR`. Thanks for the feedback, I'll publish a fix.

**Comment by kalvn** [comment]
Aaaaand done! https://github.com/kalvn/Shaarli-Material/commit/17dd870c44cd8e89fff7668411b5665a37469b74
