### ISSUE TITLE
Markdown not rendered in the Daily Shaarli

### ISSUE THREAD

**Issue by poVoq** [kalvn/Shaarli-Material#76]
I noticed that on my Daily Shaarli the markdown syntax is not converted.

This only happens when I enable this theme, with the default one it works.

Thanks for looking into it.

**Comment by kalvn** [comment]
This is related to the markdown plugin and the way I use the data on the Daily page (a bit different to what is done in the default theme). I'll see if I can adapt the markdown plugin.

**Comment by kalvn** [comment]
PR https://github.com/shaarli/Shaarli/pull/1071 has been submitted to fix this.

**Comment by poVoq** [comment]
Yeah, that works, hopefully included by default in the next version.

**Comment by poVoq** [comment]
Would be nice if the markdown was also rendered in the RSS feed of the daily. This more or less works with the non-daily feed.

**Comment by kalvn** [comment]
I created a better pull request as request by Shaarli developers: https://github.com/shaarli/Shaarli/pull/1073

@poVoq this had to be done in Shaarli directly. Can you please open an issue on Shaarli project directly?
