### ISSUE TITLE
Scrollbar issue with Bookmarklet under Firefox

### ISSUE THREAD

**Issue by poVoq** [kalvn/Shaarli-Material#78]
See: https://github.com/shaarli/Shaarli/issues/1079

The only theme I could have gotten a different from the default bookmarklet would have been this one.

Thanks for looking into it!

**Comment by kalvn** [comment]
Indeed some window features are missing. I'll fix that. In the meantime, as mentioned in the ticket you reference, you can quickly switch to default theme, add the bookmarklet from there and then switch back to Material theme.

**Comment by kalvn** [comment]
Fixed by https://github.com/kalvn/Shaarli-Material/commit/773da1e65aea595c4a3961a74d687393d8745b16
