### ISSUE TITLE
PHP Fatal error: Call to undefined function ban_canLogin()

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#79]
This morning, I did a clean install of Shaarli, building the docker image from the latest source (https://github.com/shaarli/Shaarli/pull/1185#issuecomment-407979031), and everything worked with the default theme. Later, I cloned the Material theme from Github, and everything has worked fine since, until I was logged out and wanted to log back in a few minutes ago. Bamm, empty login page. 

Docker log of the container shows the error:

```
2018/07/26 15:48:16 [error] 11#11: *276 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ban_canLogin() in /var/www/shaarli/tmp/loginform.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php:5
Stack trace:
#0 /var/www/shaarli/inc/rain.tpl.class.php(175): include()
#1 /var/www/shaarli/application/PageBuilder.php(161): RainTPL->draw('loginform')
#2 /var/www/shaarli/index.php(588): PageBuilder->renderPage('loginform')
#3 /var/www/shaarli/index.php(2194): renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\Security\SessionManager), Object(Shaarli\Security\LoginManager))
#4 {main}
  thrown in /var/www/shaarli/tmp/loginform.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php on line 5" while reading response header from upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "xxx.xxx.xxx:443"
```

Related to https://github.com/kalvn/Shaarli-Material/issues/65 or https://github.com/shaarli/Shaarli/issues/770 or https://github.com/shaarli/Shaarli/issues/711 ? 

What should I do to quick fix the issue before it gets solved here? Maybe I can modify/delete something in the docker container directly?

**Comment by immanuelfodor** [comment]
Quick & dirty fix: changed `"theme": "material",` to `"theme": "default",` in `data/config.json.php`, so I can now log back in. Changed back after login to aplpy the Material style.

**Comment by immanuelfodor** [comment]
The Shaarlier android app also couldn't login, so I deleted both references of the `ban_canLogin` function (and its corresponding `if`s) as a second quick fix.

**Comment by kalvn** [comment]
Thanks for the feedback. There was indeed an issue here. Commit https://github.com/kalvn/Shaarli-Material/commit/3b9b73dbb73f801eebf9668ec82b497bd799c59d fixes it :)

**Comment by immanuelfodor** [comment]
Thanks for the fix, it works! :)
