### ISSUE TITLE
permalink (date) not showing, or showing with a wrong fromnow date

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#8]
Hi,

1)
```
$GLOBALS['config']['MATERIAL_DATE_FROMNOW'] = true;
```
always showing `a few seconds ago`

2)
```
$GLOBALS['config']['MATERIAL_DATE_PATTERN'] = 'DD/MM/YYYY HH:mm:ss'; // optional
$GLOBALS['config']['MATERIAL_DATE_FROMNOW'] = true;
```
always showing `2015 years ago`

3)
```
$GLOBALS['config']['MATERIAL_DATE_PATTERN'] = 'DD/MM/YYYY HH:mm:ss'; // optional
$GLOBALS['config']['MATERIAL_DATE_FROMNOW'] = false;
```
showing nothing since commit `bec18701801cc140d760c261dd115fda1507a0dd` of shaarli community, which is:
```
commit bec18701801cc140d760c261dd115fda1507a0dd
Author: ArthurHoaro <arthur@hoa.ro>
Date:   Thu Mar 12 21:57:19 2015 +0100

    Define date format in templates instead of index.php.
```
If I switch to the default theme I can see the permalink even after this commit.

Thanks.
J.

PS: live examples of shaarlis using shaarli-material that have same bug as me http://river.hoa.ro/network.php you will recognize the favicon of those shaarlis

**Comment by jeekajoo** [comment]
So to make it shorter, I confirm that since `bec18701801cc140d760c261dd115fda1507a0dd` (shaarli community), your theme is broken.

**Comment by kalvn** [comment]
I wasn't planning to update this theme at each commit because it would potentially ask a lot of work. My idea was more to update at each release.
Though, I don't know when the next release is planned so I will try to work on this issue soon.

**Comment by jeekajoo** [comment]
sure, no worries @kalvn  :)

**Comment by nodiscc** [comment]
Hi all, this change (https://github.com/shaarli/Shaarli/commit/bec18701801cc140d760c261dd115fda1507a0dd) is likely here to stay. Template maintainers are now free to decide how the date should be displayed. I think it's safe to adapt your template.

**Comment by kalvn** [comment]
The "wonderful theme" convinced me :)
I will update the master branch but I will wait for the next Shaarli release to create a release on my side, so I keep the same number as for Shaarli, which should help for people running old versions.
I'm quite busy right know but I'll fix this in the next few days.

**Comment by kalvn** [comment]
The last commit fixes this : https://github.com/kalvn/Shaarli-Material/commit/5f685db8cbb218f1ed52c76cf61d02ad12d428e5
I added a parameter to set the date formatting. README is updated and I added an example options.php file as well.

I wait for your feedback before closing this issue.

**Comment by jeekajoo** [comment]
looks good :)

Note that if using MATERIAL_DATE_FROMNOW, 
MATERIAL_PHP_DATE_PATTERN and MATERIAL_DATE_PATTERN must be set. Otherwise dates are inconsistents.

So looking at https://github.com/kalvn/Shaarli-Material/blob/master/material/options.example.php.txt was *very* useful for me to make it work.

thanks @kalvn  :+1:

**Comment by kalvn** [comment]
Perfect :)
I will change a bit the README to make it more clear as people may find it weird to have to set 2 different date formats which, in addition, don't have the same notation.
Anyway thanks for the feedback.
