### ISSUE TITLE
Thumbnail() error

### ISSUE THREAD

**Issue by Chouchen** [kalvn/Shaarli-Material#80]
I'm on PHP-7.2 and while upgrading shaarli I fell into #79  (which is resolved alright). But I have another error while accessing the links list (homepage):

> PHP Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /var/www/shaarli/tmp/linklist.aeadca0864f49f08401fb0f97c162898.rtpl.php:93

I restarted Apache and PHP and I removed all files in `./tmp` without any success.

If I comment [those lines](https://github.com/kalvn/Shaarli-Material/blob/master/material/linklist.html#L72-L75), the home is working again. 

I get to the default theme after that and saw that thumbnails got updated (you got a message to re synchronized them, and they are displayed with [another method](https://github.com/shaarli/Shaarli/blob/master/tpl/default/linklist.html#L134-L145))

In [this file](https://github.com/kalvn/Shaarli-Material/blob/master/material/daily.html#L49-L54), you ignored the thumbnail altogether, maybe that's a solution too…

**Comment by kalvn** [comment]
As written [here](https://github.com/kalvn/Shaarli-Material#compatibility), Shaarli Material is not yet compatible with Shaarli v0.10.

I'm working on the upgrade but I have very little time lately so it might take a few days to be released.

**Comment by immanuelfodor** [comment]
> If I comment those lines, the home is working again.

Thanks for the quick fix @Chouchen, I didn't check the theme compatibility when pulled the latest Shaarli image, saved my instance :)

**Comment by monkeymosher** [comment]
Hi!

Any chance the update will be available soon? Thanks :))

**Comment by kalvn** [comment]
Shaarli Material v0.10.2 was [just released](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.10.2).
