### ISSUE TITLE
Private only error

### ISSUE THREAD

**Issue by Chouchen** [kalvn/Shaarli-Material#81]
I'm using PHP7.2 on Apache.

Last shaarli and material versions (just upgraded)

If I click on the "private only" button while connected, the page reload with all types of link…

I have this error in log :

> PHP Notice:  Undefined variable: privateonly in /var/www/shaarli/tmp/page.header.1256eb2eed3c60c21f4c8fc08f56e95b.rtpl.php on line 103

**Comment by kalvn** [comment]
As written [here](https://github.com/kalvn/Shaarli-Material#compatibility), Shaarli Material is not yet compatible with Shaarli v0.10.

I'm working on the upgrade but I have very little time lately so it might take a few days to be released.

**Comment by kalvn** [comment]
Shaarli Material v0.10.2 was [just released](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.10.2).
