### ISSUE TITLE
0.10.x quirks

### ISSUE THREAD

**Issue by rudeyak** [kalvn/Shaarli-Material#83]
With the new version released, there are some changes that appear to be affecting templates. 

One is that privateonly mode changed to a SESSION variable:
root@:/var/www/sha0102# grep -si privateonly */*
application/LinkFilter.php:            // ignore non private links when 'privateonly' is on.
application/Updater.php:     * Change privateonly session key to visibility.
application/Updater.php:        if (isset($_SESSION['privateonly'])) {
application/Updater.php:            unset($_SESSION['privateonly']);
root@:/var/www/sha# grep -si visibility *
CHANGELOG.md:- Update buttons used to toggle link visibility filters
CHANGELOG.md:    - explicit method visibility
index.php:        $visibility = ! empty($_SESSION['visibility']) ? $_SESSION['visibility'] : '';
index.php:        $tags = $LINKSDB->linksCountPerTag($filteringTags, $visibility);
index.php:        $visibility = ! empty($_SESSION['visibility']) ? $_SESSION['visibility'] : '';
index.php:        $tags = $LINKSDB->linksCountPerTag($filteringTags, $visibility);
index.php:    if (isset($_GET['visibility'])) {
index.php:        if ($_GET['visibility'] === 'private') {
index.php:            // Visibility not set or not already private, set private, otherwise reset it
index.php:            if (empty($_SESSION['visibility']) || $_SESSION['visibility'] !== 'private') {
index.php:                $_SESSION['visibility'] = 'private';
index.php:                unset($_SESSION['visibility']);
index.php:        } elseif ($_GET['visibility'] === 'public') {
index.php:            if (empty($_SESSION['visibility']) || $_SESSION['visibility'] !== 'public') {
index.php:                $_SESSION['visibility'] = 'public';
index.php:                unset($_SESSION['visibility']);

This would throw errors, e.g.

2018/09/03 14:48:58 [error] 690#690: *17541 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: privateonly in /var/www/sha0102/tmp/page.header.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php on line 103
PHP message: PHP Notice:  Undefined variable: privateonly in /var/www/sha0102/tmp/page.header.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php on line 103" while reading response header from upstream, client: 24.x.x.x, server: x.y.com, request: "GET /sha/?do=configure HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "x.y.com", referrer: "https://x.y.com/sha/?do=configure"

I think the fix for this is something like:

84c84
---
>                    <a href="?privateonly" class="icon-header {if="$privateonly"}filter-on{else}filter-off{/if} ripple" title="{if="$privateonly"}Click to see all links{else}Click to see only private links{/if}">
---
>                     <a href="?privateonly" class="icon-header {if="$visibility=='private'"}filter-on{else}filter-off{/if} ripple" title="{if="$visibility=='private'"}Click to see all links{else}Click to see only private links{/if}">

The other issue is with the thumbnail() function changing in 0.10.x:

PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /var/www/sha0102/tmp/linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php:93
Stack trace:
#0 /var/www/sha0102/inc/rain.tpl.class.php(175): include()
#1 /var/www/sha0102/application/PageBuilder.php(188): RainTPL->draw('linklist')
#2 /var/www/sha0102/index.php(497): PageBuilder->renderPage('linklist')
#3 /var/www/sha0102/index.php(1549): showLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(Shaarli\Security\LoginManager))
#4 /var/www/sha0102/index.php(1866): renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\Security\SessionManager), Object(Shaarli\Security\LoginManager))
#5 {main}
  thrown in /var/www/sha0102/tmp/linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php on line 93" while reading response header from upstream, client: 24.x.x.x, server: x.y.com, request: "GET /sha/?page=2 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "x.y.com", referrer: "https://x.y.com/sha/?"

The fix to that one isn't quite as straightforward, as there are multiple places where the thumbnailer function is called, and some depend on the mode the administrator selected. I'm fumbling my way through the code this weekend, will update the issue when/if I think I have something that works...

**Comment by nicolasdanelon** [comment]
this theme is not ready for shaarli 0.10, please check the following link
https://github.com/kalvn/Shaarli-Material#compatibility

**Comment by rudeyak** [comment]
Understood, happy to do whatever I can to aid with testing/debugging.

**Comment by kalvn** [comment]
Shaarli Material v0.10.2 was [just released](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.10.2).
