### ISSUE TITLE
Login page blank

### ISSUE THREAD

**Issue by mx4k** [kalvn/Shaarli-Material#85]
Good time of the day,

I followed the installation guide. After switching to the Material theme I can browse the site and the settings menu. After I log out, the login page is blank and I can't log in anymore.

Tested it in several browsers.

You can give it a try at: https://l.steinpreis.de/?do=login

**Comment by nicolasdanelon** [comment]
Are you running Shaarli version 0.9.5 ?
because the theme is not compatible with the latest versions of shaarli :(

read here https://github.com/kalvn/Shaarli-Material#compatibility

feel free to close the issue if your shaarli version is greater that 0.9.5 

have a nice day !

**Comment by kalvn** [comment]
Shaarli Material v0.10.2 was [just released](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.10.2).

**Comment by joshp23** [comment]
this is appending to me, I have correct versions set up, using 0.10.2

**Comment by kalvn** [comment]
@joshp23 Are you using Shaarli v0.10.2 as well? It looks like your Shaarli is outdated.

**Comment by joshp23** [comment]
Well, I thought I was! I installed shaarli form `stable`. I started over, installing from `latest` and everything is fine. :)
