### ISSUE TITLE
Picwall scrambled contents

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#87]
Hi, I've just updated both my Docker Shaarli and your theme, and the picwall looks like this, no thumbnails and weird contents:

![image](https://user-images.githubusercontent.com/21174107/48002251-4c8d0400-e10b-11e8-9d8d-fc07eb8c42e0.png)

If I inspect the page HTML, it seems like the images are echoed as text not in an `<img src="thumb-url" />` tag:

![image](https://user-images.githubusercontent.com/21174107/48002357-a4c40600-e10b-11e8-9dd5-126e0a2ff6aa.png)

I think this line causes the problem, or something else and it just prints the bad contents: https://github.com/kalvn/Shaarli-Material/blob/master/material/picwall.html#L16

You've mentioned there are some thumbnail updates, so this might be related: https://github.com/kalvn/Shaarli-Material/releases/tag/v0.10.2

**Comment by nicolasdanelon** [comment]
Same error here with PHP 5.6.38 and last shaarli version :(
the home page list is not working neither

**Comment by immanuelfodor** [comment]
@nicolasdanelon Homepage works for me, and it even displays the thumbnails e.g. for Youtube links. Only the picwall is broken on my instance.

**Comment by kalvn** [comment]
Indeed I totally forgot to adapt this page. I'll do it today.

**Comment by kalvn** [comment]
Commit https://github.com/kalvn/Shaarli-Material/commit/fb6f07913523aa5a502ade7ba02463fe1e7046ca should fix the issue. I didn't tested it yet though, I'll do that tonight.

**Comment by immanuelfodor** [comment]
```
From https://github.com/kalvn/Shaarli-Material
   4ccb134..fb6f079  master     -> origin/master
Updating 4ccb134..fb6f079
Fast-forward
 material/picwall.html | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)
```

@kalvn this commit made the page work, such colorful picwall, thank you very much for the quick fix!

**Comment by immanuelfodor** [comment]
@nicolasdanelon I'm using the `shaarli/shaarli:latest` Docker image, it works there fine, maybe you should give it a try, also PHP 5.6 is EOL: https://secure.php.net/supported-versions.php  + PHP7 is much faster/memory efficient

**Comment by nicolasdanelon** [comment]
@immanuelfodor thanks for your suggestion but I can't run docker or php7 in my old vps.
The thing is; the default & vintage theme works fine with my setup :) I'm just informing that the hotfix needs some review ;

**Comment by kalvn** [comment]
@nicolasdanelon Can you tell me more about the error you have?

**Comment by nicolasdanelon** [comment]
yes @kalvn I'm sorry
<b>Fatal error</b>:  Call to undefined function thumbnail() in <b>/home/shaarli/public_html/links/tmp/linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php</b> on line <b>93</b><br />

**Comment by immanuelfodor** [comment]
@nicolasdanelon you probably need to delete the contents of the tmp folder after the theme update to let the template cache build up from the new files: 

```bash
rm -rf home/shaarli/public_html/links/tmp/*
```

**Comment by nicolasdanelon** [comment]
wtf @immanuelfodor I've already do that
```
-rwxr-xr-x  1 shaarli shaarli  236 Dec  1  2016 .htaccess
-rw-r--r--  1 shaarli shaarli 2.4K Nov  5 15:49 feed.rss.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php
-rw-r--r--  1 shaarli shaarli 3.3K Nov  5 15:40 includes.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php
-rw-r--r--  1 shaarli shaarli  10K Nov  5 15:40 linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php
-rw-r--r--  1 shaarli shaarli 1.4K Nov  5 15:40 linklist.paging.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php
-rw-r--r--  1 shaarli shaarli 2.0K Nov  5 15:40 page.footer.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php
-rw-r--r--  1 shaarli shaarli  12K Nov  5 15:40 page.header.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php
-rw-r--r--  1 shaarli shaarli 2.1K Nov  5 15:40 picwall.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php
```

**Comment by immanuelfodor** [comment]
These are the regenerated files or before the deletion or those you were unable to delete? :)

**Comment by nicolasdanelon** [comment]
regenerated

**Comment by immanuelfodor** [comment]
I also have the `linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php` flle but there is nothing on the 93rd line: 

![screenshot_20181105-203100](https://user-images.githubusercontent.com/21174107/48021821-ccca5e00-e139-11e8-9048-60dff9aff457.jpg)

**Comment by kalvn** [comment]
That's super weird. I have the same file than you `linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php` but I have nothing on line 93 and there's no calls to function `thumbnail` anywhere in the file.

**Comment by nicolasdanelon** [comment]
I do.. I have something like this:
```
<?php $thumb=$this->var['thumb']=thumbnail($value1["url"]);?>
```

ok, I'll reset my installation

**Comment by kalvn** [comment]
It clearly looks like old code: https://github.com/kalvn/Shaarli-Material/blob/21802591701cc929e3dc69badd676ed555a48a83/material/linklist.html#L72

It looks like the new version of the theme is not properly used.

**Comment by nicolasdanelon** [comment]
yeah, my bad, I had two theme installations :( haha symbolic link issues
