### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Nebucatnetzer** [kalvn/Shaarli-Material#89]
Just wanted to say thank you for the great theme.
It looks really nice and works well on both mobile and normal computers.
IMO it should be the default theme of Shaarli.

The installation worked without a problem.

**Comment by kalvn** [comment]
Thanks a lot! That's really great to see that what I do is helpful and appreciated :)

**Comment by rudeyak** [comment]
It is!!

**Comment by nicolasdanelon** [comment]
I love this theme too, you already know that :P

**Comment by kalvn** [comment]
I do :P

Thanks!

**Comment by Nebucatnetzer** [comment]
@kalvn it's the least I could do :)

**Comment by Arrappathor** [comment]
Indeed, thank you very much for this clean and beautiful theme. It is a pleasure.

**Comment by NicolasBrosse** [comment]
Love it too.
Thank you.

**Comment by kalvn** [comment]
I'll close it now in order to clean things up a bit, but thanks a lot for the support once again :)
