### ISSUE TITLE
Error on Tag Page 

### ISSUE THREAD

**Issue by msone** [kalvn/Shaarli-Material#93]
I am using Shaarli v0.10.4 with the current material theme. If a tag with a # in front of it is used, there is an error message: "**Notice: Undefined index: thumbnail in include...rtpl.php on line 27**".

Here is the error message: https://imgur.com/a/ifXEWv4
And here is the line 27: https://imgur.com/a/qTIpcsx

Thumbnails are disabled in the settings.

**Comment by kalvn** [comment]
Thanks for the finding! Commit https://github.com/kalvn/Shaarli-Material/commit/84e6d1189ca723793a9190cc70e0a92c853d1175 should fix the issue.
