### ISSUE TITLE
Shaarli v0.11.X support

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#94]
Hi, thanks for this wonderful theme, been using it since day 1.  Any chance supporting the new namespaced 0.11 line in the near future? I don't want to upgrade until I'm not sure if it will work, and it's also holding back two of my plugins from update since I'm only migrating after your theme is fully compatible with upstream (sorry for the push 😃).

**Comment by immanuelfodor** [comment]
Oh, I've just seen the other branch: https://github.com/kalvn/Shaarli-Material/tree/support-v011 but it was not merged, so I suppose it's not yet ready.

**Comment by kalvn** [comment]
I actually didn't work on it for a while. This branch only brings the additional actions when you select several links so even without, the master branch of the theme should work pretty well with Shaarli v0.11.X. The theme contains no PHP code so namespaces shouldn't be an issue.

**Comment by immanuelfodor** [comment]
Thank you, it's indeed working fine! :)
