### ISSUE TITLE
Unable to login with latest Shaarli

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#95]
Hi @kalvn, 

I've updated my Shaarli to the latest master commit, and it seems somewhere along the months passed by, there is something that broke your superb theme :(

```
shaarli    | 2020/03/18 05:13:56 [error] 10#10: *74 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: user_can_login in /var/www/shaarli/tmp/loginform.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php on line 5
shaarli    | PHP message: PHP Notice:  Undefined variable: user_can_login in /var/www/shaarli/tmp/loginform.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php on line 22" while reading response header from upstream, client: 192.168.1.10, server: , request: "GET /login? HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "shaarli.local", referrer: "https://shaarli.local/login?"
```

The theme displays "You have been banned after too many failed login attempts. Try again later." but there is no ipbans.php at all, and I can see the above PHP log in Docker. The Shaarlier Android app also can't login because of this.

**Comment by kalvn** [comment]
It's been a while I didn't work on it, and you're right, there was an update of the login page template in January on Shaarli. I'll try to work on a fix this week. In the meantime, I recommend sticking to v0.11.1 of Shaarli instead of the last master.

**Comment by immanuelfodor** [comment]
Thank you! Yes, I reverted back to my previous working docker image after the rebuild.

**Comment by immanuelfodor** [comment]
Hi @kalvn , I've seen the new release, and I'd like to know if it contains a fix to this issue as well?
https://github.com/kalvn/Shaarli-Material/releases/tag/v0.11.0

**Comment by kalvn** [comment]
Hello @immanuelfodor , no it doesn't, because version 0.11.0 of Shaarli didn't have the issue.

But I'm now working on catching up with latest commits on master of Shaarli so the last commits on **dev** branch do fix the issue. Though I suggest to wait that I merge dev branch into master so that you get all updates and possible fixes at once.

**Comment by immanuelfodor** [comment]
Okay, thanks!

**Comment by kalvn** [comment]
I just merged my dev branch with master. Feel free to use the master branch now. It may not be perfectly stable though.

**Comment by immanuelfodor** [comment]
Thank you, I can confirm now it works fine with the latest master; which is https://github.com/shaarli/Shaarli/commit/810f0f6c96b6d26e22164027185c5996b425816c as of now.
